version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/raivqqe/hamt.go
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt -y update --fix-missing
            apt -y install rake
      - run:
          name: Dependencies
          command: rake deps
      - run:
          name: Lint
          command: rake lint
      - run:
          name: Build
          command: rake build
      - run:
          name: Test
          command: |
            rake test
            curl -sSL https://codecov.io/bash | bash
      - run:
          name: Benchmark
          command: rake bench
